<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FastEndpoints"/>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Modules.Catalog.Application\Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Endpoints\Common.Endpoints.csproj" />
  </ItemGroup>
</Project>