# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  mercadopresoapi:
    image: mercadopresoapi
    build:
      context: .
      dockerfile: src/MercadoPreso.Api/Dockerfile
    ports:
      - 5113:5113
