# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  mercadopresoapi:
    image: erickbueno/mercadopreso-api:latest
    ports:
      - 5113:5113
