# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: mercado-preso-database
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: mercado_preso
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - name=value
  mercadopresoapi:
    image: erickbueno/mercadopreso-api:latest
    ports:
      - 5113:5113
    depends_on:
      - postgres
    networks:
      - backend
  
volumes:
  database:

networks:
  backend:
  